// main.js -- boot: load the settings and the data, fill every list, wire the features.
//   site.json          hand-edited settings (YouTube id, hide_sections)
//   data/game.json     generated by sitedata.py from the game's tables
//   data/trailer.json  generated by trailer.py (optional)

import {sections} from "./sections.js";
import {renderTrailer} from "./trailer.js";
import {initFilter} from "./filter.js";
import {initLightbox} from "./lightbox.js";
import {fmt} from "./ui.js";

const load = (url) => fetch(url, {cache: "no-cache"}).then((r) => (r.ok ? r.json() : null)).catch(() => null);

async function boot() {
  const [site, data, trailer] = await Promise.all([load("site.json"), load("data/game.json"),
                                                   load("data/trailer.json")]);
  const cfg = site || {};
  for (const id of cfg.hide_sections || []) {
    const s = document.getElementById(id);
    if (s) { s.hidden = true; s.dataset.off = "1"; }
    const a = document.querySelector(`nav a[href="#${id}"]`);
    if (a) a.hidden = true;
  }
  renderTrailer(document.querySelector('[data-render="trailer"]'),
                document.querySelector('[data-render="trailer-links"]'), cfg, trailer);
  if (!data) {
    document.body.insertAdjacentHTML("afterbegin",
      '<p class="note">data/game.json did not load -- run python sitegen.py --data</p>');
    return;
  }
  for (const el of document.querySelectorAll("[data-count]")) el.textContent = fmt.int(data.counts[el.dataset.count]);
  for (const el of document.querySelectorAll("[data-fact]")) {
    const v = data.numbers.facts[el.dataset.fact];
    if (v == null) el.closest(".fig")?.remove(); else el.textContent = fmt.int(v);
  }
  for (const el of document.querySelectorAll("[data-render]")) {
    const name = el.dataset.render;
    if (name.startsWith("trailer")) continue;
    const fn = sections[name];
    if (!fn) { console.warn("no section renderer for", name); continue; }
    try { fn(el, data, {site: cfg, trailer}); }
    catch (e) { console.error("section", name, "failed:", e); }
  }
  const q = document.getElementById("q");
  if (q) q.placeholder = `Filter ${fmt.int(data.counts.carded)} models: try topple, torpedo, arctic, mech`;
  initFilter(q, document.getElementById("qn"));
  initLightbox(document.getElementById("lb"));
}

boot();
